---
- name: Printing the environment​ variable in Ansible
  debug:
    msg: "{{ lookup('env','USER') }}"
  register: username

- name: clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh
       update=no

- name: check if .zshrc exists
  stat: path=~/.zshrc
  register: zshrc

# Run only when the has been changed
- name: copy zshrc to user home
  copy: src=".zshrc"
        dest=~/
        force=yes
        backup=yes
  when: not zshrc.stat.exists

- name: Validating the current shell
  shell: echo $SHELL
  register: isSHELL

- debug:
    msg: "The Current Shell is: {{ isSHELL.stdout }}"

- name: change user shell to zsh
  become: true
  become_user: root
  command: chsh -s /bin/zsh "{{ lookup('env','USER') }}"
  changed_when: isSHELL.stdout.find("/bin/zsh")|bool == false
